version: '3.8'

services:
  frontend:
    build: ./nft-whale-tracker-frontend
    container_name: nft-whale-tracker-frontend
    ports:
      - "80:80"
    volumes:
      - ./nft-whale-tracker-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./nft-whale-tracker-backend
    container_name: nft-whale-tracker-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 