server:
  port: 8886
  servlet:
    context-path: /api

spring:
  application:
    name: nft-whale-tracker-api

paimon:
  catalog:
    type: paimon
    metastore: hive
    uri: thrift://192.168.254.133:9083
    hive-conf-dir: /opt/software/apache-hive-3.1.3-bin/conf
    hadoop-conf-dir: /opt/software/hadoop-3.1.3/etc/hadoop
    warehouse: hdfs:////user/hive/warehouse

logging:
  level:
    root: INFO
    org.bigdatatechcir.whale: DEBUG
    org.apache.paimon: INFO

cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  max-age: 3600 